/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.22).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.demo.hotelbooking.controller;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-04-13T23:17:45.935419500+05:30[Asia/Calcutta]")
@Api(value = "HotelBooking", description = "the HotelBooking API")
public interface HotelBookingApi {

    @ApiOperation(value = "check if the bonus points of the passed userId is sufficient and do the booking/change the status.", nickname = "bookingOperation", notes = "depending upon the userid's bonus point and change the status of booking.", response = Object.class, tags={ "hotel-booking", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Object.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Object.class),
        @ApiResponse(code = 400, message = "Bad request when the user do not pass the correct input or format", response = Object.class) })
    @RequestMapping(value = "/bookHotel/{hotelId}/{userId}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Object> bookingOperation(@ApiParam(value = "Supported Content Type- application/json" ,required=true) @RequestHeader(value="Accept", required=true) String accept
,@ApiParam(value = "Provides the userId who wants to do the bookings",required=true) @PathVariable("userId") String userId
,@ApiParam(value = "Provides the hotelId for which booking request has been raised",required=true) @PathVariable("hotelId") String hotelId
);

}

